#%RAML 1.0 Library
usage:
traits:
  transactionid: !include /Commons/Traits/headers_transactionId_trait.raml
  companyName: !include /Commons/Traits/queryParam_companyName_trait.raml
  departureLocation: !include /Commons/Traits/queryParams_departureLocation_trait.raml
  destinationLocation: !include /Commons/Traits/queryParam_destinationLocation_trait.raml 
  requestTimezone: !include  /Commons/Traits/queryParam_requestTimezone_trait.raml